frollous/frollo-swift-sdk

- Cartfile
- Cartfile.resolved
- Package.swift
- Sources/Authentication/Authentication.swift
- Sources/Error/NetworkError.swift
- Sources/Network/API/APIService.swift
- Sources/Network/API/Requests/APIService+Aggregation.swift
- Sources/Network/API/Requests/APIService+Bills.swift
- Sources/Network/API/Requests/APIService+User.swift
- Sources/Network/Network.swift
- Sources/Network/OAuth2/OAuth2Service.swift
- Tests/Aggregation/AggregationTests.swift
- Tests/Events/EventsTests.swift
- Tests/Network/API/CDRRequestTests.swift
- Tests/Network/API/DeviceRequestTests.swift
- Tests/Network/API/EventsRequestTests.swift
- Tests/Network/NetworkAuthenticatorTests.swift
- Tests/User/UserManagementTests.swift
Did necessary changes to support Alamofire 5.x
> Feature/update to 5.x

- Sources/Aggregation/Aggregation.swift
With our pagination logic, the transaction cache updating code is complicated. I realised when I was trying to explain the logic to Deepak few weeks ago. I tried my best to explain the logic in comments. Please let me know if it doesn't makes sense and can be explained better :D
> Add comments to explain transaction predicates logic

- Sources/Budgets/Budgets.swift
- Sources/Events/Events.swift
- Tests/Events/EventsTests.swift
[VPA-340] Add current period ready event in SDK
[VPA-340]: https://frollo.atlassian.net/browse/VPA-340
> [VPA-340] Add current period ready event in SDK

- Tests/Events/EventsTests.swift
[SDK-471] Fix failing tests
[SDK-471]: https://frollo.atlassian.net/browse/SDK-471
> [SDK-471] Fix failing tests

- Sources/Bills/Bills.swift
- Tests/Bills/BillsTests.swift
- Tests/Model/API/Bills/APIBillCreateRequest+Test.swift
- Tests/Network/API/BillsRequestTests.swift
[SDK-474] Add dueAmount in createBill method
[SDK-474]: https://frollo.atlassian.net/browse/SDK-474
> [SDK-474] Add dueAmount in createBill method

- Sources/Model/Transient/TransactionFilter.swift
- Tests/Model/Transient/TransactionFilter+Tests.swift
[SDK-476] 
[SDK-476]: https://frollo.atlassian.net/browse/SDK-476
> [SDK-476] Add BillID Filter to Transactions API

- Tests/Network/NetworkAuthenticatorTests.swift
[SDK-482] Fix failing test by increasing timeout
[SDK-482]: https://frollo.atlassian.net/browse/SDK-482
> [SDK-482] Fix failing test by increasing timeout

- Sources/Aggregation/Aggregation.swift
- Sources/Model/API/CDR/APICDRConsentRequest.swift
- Sources/Model/Transient/CDRConsentForm.swift
- Tests/CDR/CDRTests.swift
[FROLLO-3009]
[FROLLO-3009]: https://frollo.atlassian.net/browse/FROLLO-3009
> [FROLLO-3009] Added existing consent id field, refactored update consent functions

- FrolloSDK.xcodeproj/project.pbxproj
- Sources/FrolloSDK.swift
- Sources/Model/API/Shared/APIErrorResponse.swift
- Tests/Error/APIErrorTests.swift
- Tests/FrolloSDKTests.swift
- Tests/Resources/API/Error/Payments/error_payment_account_restricted.json
- Tests/Resources/API/Error/Payments/error_payment_insufficient_funds.json
- Tests/Resources/API/Error/Payments/error_payment_invalid_account.json
- Tests/Resources/API/Error/Payments/error_payment_invalid_biller_code.json
- Tests/Resources/API/Error/Payments/error_payment_invalid_bpay.json
- Tests/Resources/API/Error/Payments/error_payment_invalid_bsb.json
- Tests/Resources/API/Error/Payments/error_payment_invalid_crn.json
- Tests/Resources/API/Error/Payments/error_payment_invalid_date.json
- Tests/Resources/API/Error/Payments/error_payment_invalid_destination_account.json
- Tests/Resources/API/Error/Payments/error_payment_invalid_pay_anyone.json
- Tests/Resources/API/Error/Payments/error_payment_invalid_source_account.json
- Tests/Resources/API/Error/Payments/error_payment_invalid_transfer.json
- Tests/Resources/API/Error/Payments/error_payment_other.json
- Tests/Resources/API/Error/Payments/error_payment_processor.json
- Tests/Resources/API/Error/Payments/error_payment_processor_connectivity.json
[SDK-497] Payment Errors
[SDK-497]: https://frollo.atlassian.net/browse/SDK-497
> [SDK-497] Payment Errors

- FrolloSDK.xcodeproj/project.pbxproj
- Resources/Localization/en.lproj/Localizable.strings
- Sources/Error/APIError.swift
- Sources/Model/API/Shared/APIErrorResponse.swift
- Sources/Network/API/Requests/APIService+Payments.swift
- Sources/Network/HTTPHeader.swift
- Sources/Network/Network.swift
- Sources/Payments/Payments.swift
- Tests/Error/APIErrorTests.swift
- Tests/Network/NetworkAuthenticatorTests.swift
- Tests/Resources/API/Error/Payments/error_payment_invalid_otp.json
- Tests/Resources/API/Error/Payments/error_payment_missing_otp.json
[VPA-554]
[VPA-554]: https://frollo.atlassian.net/browse/VPA-554
> [VPA-554] OTP for payment APIs

- .circleci/config.yml
[FROLLO-3199] Add JIRA integration to iOS CI build
[FROLLO-3199]: https://frollo.atlassian.net/browse/FROLLO-3199
> Add CircleCI JIRA integration

- Sources/Model/Transient/Payments/PayAnyoneResponse.swift
- Sources/Model/Transient/Payments/PaymentTransferResponse.swift
- Tests/Network/NetworkAuthenticatorTests.swift
- Tests/Payments/PaymentsTests.swift
- Tests/Resources/API/Payments/payment_transfer_response.json
[SDK-506] Update Payment API responses and Fix failing tests
[SDK-506]: https://frollo.atlassian.net/browse/SDK-506
> [SDK-506] Update Payment API responses and Fix failing tests

- Sources/Aggregation/Aggregation.swift
- Sources/Model/API/Aggregation/APIProviderAccountUpdateRequest.swift
- Tests/Aggregation/AggregationTests.swift
This PR has already been merged but not sure why the changes haven't been reflected
> Add consent ID to update provider account

- Cartfile.resolved
- Sources/Logging/ConsoleLogger.swift
- Sources/Logging/Log.swift
- Sources/Network/API/Requests/APIService+Device.swift
- Sources/User/UserManagement.swift
- Tests/Logging/LogTests.swift
- Tests/User/UserManagementTests.swift
[VPA-643]
To send feedback logs
[VPA-643]: https://frollo.atlassian.net/browse/VPA-643
> Expose device/log API

- Sources/Budgets/Budgets.swift
- Sources/Model/API/Budget/APIBudgetCreateRequest.swift
- Tests/Budgets/BudgetsTests.swift
- Tests/Model/API/Budgets/APIBudgetCreateRequest+Test.swift
[SDK-460] Remove tracking_type from create budget
[SDK-460]: https://frollo.atlassian.net/browse/SDK-460
> [SDK-460] Remove tracking_type from create budget

- Sources/Model/Core Data/User/User+CoreDataClass.swift
> Address initilizer

- FrolloSDK.xcodeproj/project.pbxproj
- Sources/Model/API/User/APIUserPayIDOTPRequest.swift
- Sources/Model/API/User/APIUserPayIDOTPResponse.swift
- Sources/Model/API/User/APIUserPayIDResponse.swift
- Sources/Model/API/User/APIUserRegisterPayIDRequest.swift
- Sources/Model/API/User/APIUserRegisterPayIDResponse.swift
- Sources/Model/API/User/APIUserRemovePayIDRequest.swift
- Sources/Network/API/Endpoints/UserEndpoint.swift
- Sources/Network/API/Requests/APIService+User.swift
- Sources/User/UserManagement.swift
- Tests/Resources/API/User/user_get_payid.json
- Tests/Resources/API/User/user_register_payid.json
- Tests/Resources/API/User/user_request_payid_otp.json
- Tests/User/UserManagementTests.swift
[SDK-535] 
[SDK-536] 
[SDK-537] 
[SDK-538] 
[SDK-535]: https://frollo.atlassian.net/browse/SDK-535
[SDK-536]: https://frollo.atlassian.net/browse/SDK-536
[SDK-537]: https://frollo.atlassian.net/browse/SDK-537
[SDK-538]: https://frollo.atlassian.net/browse/SDK-538
> PayID Management APIs

- FrolloSDK.xcodeproj/project.pbxproj
- Sources/Contacts/Contacts.swift
- Sources/Model/API/Contacts/APIContactResponse.swift
- Sources/Model/API/Payments/APINPPPaymentResponse.swift
- Sources/Model/API/Payments/APIPayIDPaymentRequest.swift
- Sources/Model/API/User/APIUserRegisterPayIDRequest.swift
- Sources/Model/API/User/APIUserRemovePayIDRequest.swift
- Sources/Model/Core Data/Contacts/PayIDContact+CoreDataClass.swift
- Sources/Model/Transient/PayID/AccountPayIDResponse.swift
- Sources/Model/Transient/PayID/PayIDResponse.swift
- Sources/Model/Transient/Payments/PayAnyoneResponse.swift
- Sources/Model/Transient/Payments/PayIDPaymentResponse.swift
- Sources/Network/API/Endpoints/PaymentsEndpoint.swift
- Sources/Network/API/Requests/APIService+Payments.swift
- Sources/Network/API/Requests/APIService+User.swift
- Sources/Payments/Payments.swift
- Sources/User/UserManagement.swift
- Tests/Contacts/ContactsTests.swift
- Tests/Payments/PaymentsTests.swift
- Tests/Resources/API/Contacts/create_payID_contact.json
- Tests/Resources/API/Contacts/get_contacts.json
- Tests/Resources/API/Contacts/update_payID_contact.json
- Tests/Resources/API/Payments/npp_payment_response.json
- Tests/Resources/API/Payments/pay_anyone_response.json
- Tests/User/UserManagementTests.swift
[SDK-547] 
[SDK-549] 
[SDK-547]: https://frollo.atlassian.net/browse/SDK-547
[SDK-549]: https://frollo.atlassian.net/browse/SDK-549
> NPP PayAnyone & PayID payment APIs

- FrolloSDK.xcodeproj/project.pbxproj
- Sources/Model/API/Payments/APIVerifyPayIDRequest.swift
- Sources/Model/Transient/Payments/PayAnyoneResponse.swift
- Sources/Model/Transient/Payments/PayIDPaymentResponse.swift
- Sources/Model/Transient/Payments/PaymentTransferResponse.swift
- Sources/Model/Transient/Payments/VerifyPayIDResponse.swift
- Sources/Network/API/Endpoints/PaymentsEndpoint.swift
- Sources/Network/API/Requests/APIService+Payments.swift
- Sources/Payments/Payments.swift
- Tests/Payments/PaymentsTests.swift
- Tests/Resources/API/Payments/npp_payment_response.json
- Tests/Resources/API/Payments/verify_payID_response.json
[SDK-546] 
[SDK-546]: https://frollo.atlassian.net/browse/SDK-546
> Verify PayID API; Adapt to changes in [FROLLO-4233]

- Sources/Network/API/Endpoints/KYCEndpoint.swift
[SDK-564] Adjusting to KYC endpoint change
[SDK-564]: https://frollo.atlassian.net/browse/SDK-564
> [SDK-564] Adjusting to KYC endpoint change

- Sources/FrolloSDK/Events/Events.swift
- Sources/FrolloSDK/Model/Transient/NotificationPayload.swift
- Sources/FrolloSDK/User/UserManagement.swift
- Tests/Events/EventsTests.swift
- Tests/Model/Transient/NotificationPayload+Test.swift
[SDK-566] Onboarding step event payload name
[SDK-566]: https://frollo.atlassian.net/browse/SDK-566
> [SDK-566] Onboarding step event payload name

- Sources/FrolloSDK/Aggregation/Aggregation.swift
There is also a fix on frollo-link-ios.
> FROLLO-4685: Fix issue of Provider list index not showing (SDK fix)

- Sources/FrolloSDK/Authentication/OAuth2Authentication.swift
- Sources/FrolloSDK/Logging/Log.swift
- Sources/FrolloSDK/Model/OAuth2/OAuth2TokenRevokeRequest.swift
> FROLLO-4750: add domain in the request of revoking access token

- FrolloSDK.xcodeproj/project.pbxproj
- Sources/FrolloSDK/Budgets/Budgets.swift
- Sources/FrolloSDK/Network/API/Endpoints/BudgetsEndPoint.swift
- Sources/FrolloSDK/Network/API/Requests/APIService+Budgets.swift
- Tests/Budgets/BudgetsTests.swift
- Tests/Resources/API/Budgets/budget_periods_valid.json
- Tests/Resources/API/Budgets/budget_periods_valid_page_2.json
[SDK-586] 
[SDK-586]: https://frollo.atlassian.net/browse/SDK-586
> Fix Budget Period List response; Add status query param

- Sources/FrolloSDK/Extensions/Error+Logging.swift
- Tests/Error/NetworkErrorTests.swift
Send file in error log and add more errors to exclude in log
> Send file in error log and add more errors to exclude in log

- Sources/FrolloSDK/Aggregation/Aggregation.swift
- Sources/FrolloSDK/FrolloSDK.swift
- Sources/FrolloSDK/Model/Core Data/Budgets/Budget+CoreDataClass.swift
- Sources/FrolloSDK/Model/Core Data/Goals/Goal+CoreDataClass.swift
- Sources/FrolloSDK/Model/Core Data/Messages/Message+CoreDataClass.swift
- Sources/FrolloSDK/Network/API/Requests/APIService+Aggregation.swift
- Sources/FrolloSDK/Network/API/Requests/APIService+Bills.swift
- Sources/FrolloSDK/Network/API/Requests/APIService+Budgets.swift
- Sources/FrolloSDK/Network/API/Requests/APIService+Contacts.swift
- Sources/FrolloSDK/Network/API/Requests/APIService+Device.swift
- Sources/FrolloSDK/Network/API/Requests/APIService+Goals.swift
- Sources/FrolloSDK/Network/API/Requests/APIService+ManagedProduct.swift
- Sources/FrolloSDK/Network/API/Requests/APIService+User.swift
- Sources/FrolloSDK/Network/OAuth2/OAuth2Service.swift
- Tests/FrolloSDKTests.swift
[SDK-609] Handle empty response, control refreshing and error logging
[SDK-609]: https://frollo.atlassian.net/browse/SDK-609
> [SDK-609] Handle empty response, control refreshing and error logging

- Sources/FrolloSDK/Budgets/Budgets.swift
- Sources/FrolloSDK/Extensions/Result.swift
- Sources/FrolloSDK/FrolloSDK.swift
- Sources/FrolloSDK/Goals/Goals.swift
- Tests/Budgets/BudgetsTests.swift
- Tests/Goals/GoalsTests.swift
[SDK-499] Return GoalID and BudgetID
[SDK-499]: https://frollo.atlassian.net/browse/SDK-499
> [SDK-499] Return GoalID and BudgetID

- FrolloSDK.xcodeproj/project.pbxproj
- Sources/FrolloSDK/Model/Transient/AddressAutocomplete.swift
- Sources/FrolloSDK/Network/API/Endpoints/UserEndpoint.swift
- Sources/FrolloSDK/Network/API/Requests/APIService+User.swift
- Sources/FrolloSDK/User/UserManagement.swift
- Tests/Resources/API/User/address_autocomplete.json
- Tests/Resources/API/User/address_get.json
- Tests/User/UserManagementTests.swift
[SDK-610] [SDK-611] Address autocomplete and get API
[SDK-610]: https://frollo.atlassian.net/browse/SDK-610
[SDK-611]: https://frollo.atlassian.net/browse/SDK-611
> [SDK-610] [SDK-611] Address autocomplete and get API

- Sources/FrolloSDK/Extensions/Error+Logging.swift
[SDK-615] 
[SDK-615]: https://frollo.atlassian.net/browse/SDK-615
> Add line number & function to error log

- Sources/FrolloSDK/Network/API/Requests/APIService+User.swift
- Sources/FrolloSDK/Network/Network.swift
- Tests/Network/NetworkTests.swift
- Tests/Resources/API/User/user_details_complete.json
[SDK-616]
[SDK-616]: https://frollo.atlassian.net/browse/SDK-616
>  Update API version & User DOB date format

- Sources/FrolloSDK/Model/API/Goals/APIGoalCreateRequest.swift
- Sources/FrolloSDK/Model/Core Data/Goals/Goal+CoreDataClass.swift
- Tests/Goals/GoalsTests.swift
- Tests/Network/API/GoalsRequestTests.swift
- Tests/Resources/API/Goals/goal_id_3211.json
[SDK-1701] Goal target changes
> [SDK-1701] Goal target changes

- Sources/FrolloSDK/User/UserManagement.swift
- Tests/User/UserManagementTests.swift
[SDK-636] PayID Notifications
[SDK-636]: https://frollo.atlassian.net/browse/SDK-636
> [SDK-636] PayID Notifications

- FrolloSDK.xcodeproj/project.pbxproj
- Sources/FrolloSDK/Aggregation/Aggregation.swift
- Sources/FrolloSDK/Model/Transient/Payments/BPAYPaymentResponse.swift
- Sources/FrolloSDK/Model/Transient/Payments/PayAnyoneResponse.swift
- Sources/FrolloSDK/Model/Transient/Payments/PayIDPaymentResponse.swift
- Sources/FrolloSDK/Model/Transient/Payments/PaymentLimit.swift
- Sources/FrolloSDK/Model/Transient/Payments/PaymentTransferResponse.swift
- Sources/FrolloSDK/Network/API/Endpoints/AggregationEndpoint.swift
- Sources/FrolloSDK/Network/API/Requests/APIService+Aggregation.swift
- Tests/Aggregation/AggregationTests.swift
- Tests/Resources/API/Aggregation/limits_valid.json
[SDK-650] Payment Limits API integration
[SDK-650]: https://frollo.atlassian.net/browse/SDK-650
> [SDK-650] Payment Limits API integration
